services:
  db:
    image: postgres:16
    container_name: spotify-connect-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: spotify_connect
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - neto_projects:/var/lib/postgresql/data
volumes:
  neto_projects: