server:
  port: 8081
  error:
    include-stacktrace: on_param

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spotify_connect
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

